# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dfuzz"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tduehr", "Dino Dai Zovi"]
  s.date = "2013-06-17"
  s.description = "Fuzzing payload generators for pentesting"
  s.email = "td@matasano.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/dfuzz.rb",
    "lib/dfuzz/generator.rb",
    "test/helper.rb",
    "test/test_dfuzz.rb"
  ]
  s.homepage = "http://github.chi.matasano.com/td/dfuzz"
  s.licenses = ["private"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Fuzz generators"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

