# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: dfuzz 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "dfuzz"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["tduehr", "Dino Dai Zovi"]
  s.date = "2016-11-03"
  s.description = "Fuzzing payload generators for pentesting"
  s.email = "timur.duehr@nccgroup.trust"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "dfuzz.gemspec",
    "lib/dfuzz.rb",
    "lib/dfuzz/block.rb",
    "lib/dfuzz/char.rb",
    "lib/dfuzz/diagonal.rb",
    "lib/dfuzz/fudge.rb",
    "lib/dfuzz/generator.rb",
    "lib/dfuzz/generator18.rb",
    "lib/dfuzz/integer.rb",
    "lib/dfuzz/sequential.rb",
    "lib/dfuzz/string.rb",
    "test/helper.rb",
    "test/test_dfuzz.rb"
  ]
  s.homepage = "http://github.com/tduehr/dfuzz"
  s.rubygems_version = "2.5.1"
  s.summary = "Fuzz generators"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 2.1.2"])
      s.add_development_dependency(%q<yard>, ["~> 0.9.5"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.1.2"])
      s.add_dependency(%q<yard>, ["~> 0.9.5"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.1.2"])
    s.add_dependency(%q<yard>, ["~> 0.9.5"])
  end
end

